### ISSUE TITLE
Uninitialized constant Jumpstart::AdminPanelHelpers

### ISSUE THREAD

**Issue by samuelcouch** [avo-hq/jumpstart-pro-app-template#1]
Using a fresh install of Jumpstart Pro latest (https://github.com/jumpstart-pro/jumpstart-pro-rails/tree/fb47f99f8212b1ae4aea0b9696aa233ad6ec6b01). I added Avo with `bin/rails app:template LOCATION=https://v3.avohq.io/templates/jumpstart-pro.template`

There is a NameError `uninitialized constant Jumpstart::AdminPanelHelpers`

* http://127.0.0.1:3000/avo/resources/subscriptions
* http://127.0.0.1:3000/avo/resources/plans
* http://127.0.0.1:3000/avo/resources/customers
* http://127.0.0.1:3000/avo/resources/charges

I noticed these routes are all related to payment stuff, I'm not sure if it's because that is not configured (it is truly a clean install).

All other resources load just fine.

**Comment by adrianthedev** [comment]
Fixed by https://github.com/avo-hq/jumpstart-pro-app-template/commit/ed30ac6e189a0964d25165b5283bb6a53593a729

Thanks for reporting it!
I'm glad everything (else) works nicely!

You know where to [find us](https://avo.cool/repo) if we can help.
